apiVersion: apps/v1
kind: Deployment
metadata:
  name: avif-converter
  namespace: webapps
  labels:
    app: avif-converter
spec:
  replicas: 1  # Higher replica count for conversion workload
  selector:
    matchLabels:
      app: avif-converter
  template:
    metadata:
      labels:
        app: avif-converter
    spec:
      containers:
      - name: avif-converter
        image: ghcr.io/ekskog/any2avif:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 600  # 10 minutes
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
        resources:
          requests:
            memory: "512Mi"  # Higher baseline for image processing
            cpu: "200m"
          limits:
            memory: "3Gi"    # Much higher for large image conversions (24MP+ images)
            cpu: "2000m"     # Higher CPU for AVIF encoding
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MAX_FILE_SIZE
          value: "52428800"  # 50MB in bytes
        - name: QUALITY
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: avif-converter
  namespace: webapps
  labels:
    app: avif-converter
spec:
  selector:
    app: avif-converter
  ports:
  - port: 3002  # Match the port in photovault-api configmap
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP  # Internal service only
